### ISSUE TITLE
too many re-renders when changing keys

### ISSUE THREAD

**Issue by TkDodo** [TanStack/query#3772]
### Describe the bug

When changing the query key, react-query re-renders the component two times with the exact same states

### Your minimal, reproducible example

v4: https://codesandbox.io/s/react-query-re-renders-t2z4u8, v3: https://codesandbox.io/s/react-query-re-renders-v3-cfo8y4

### Steps to reproduce

- Open the sandbox and inspect the console
- on page load, you'll see two renders (loading and success): 🆗 
- click the `next` button
- you'll see 3 additional renders
  - loading: 🆗 
  - loading: 🚫 
  - success: 🆗

The second "loading" render has the exact same state as the previous one and is unnecessary.

This happens on v17 and v18 of react, and in v3 and v4 of react-query.
It also has nothing to do with extra renders in dev-mode and strict effects (the example doesn't use strict mode), and it can also be reproduced when the logging is moved to an effect. The component _really_ renders twice.

### Expected behavior

we should see two renders instead of three:

  - loading: 🆗 
  - success: 🆗

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="591" alt="Screenshot 2022-07-02 at 08 06 22" src="https://user-images.githubusercontent.com/1021430/176988830-b18c7755-6400-4096-8e0f-44971231b9ad.png">

### Platform

independent (I'm on macos & brave)

### react-query version

v3 and v4

### Additional context

first reported on stackoverflow: https://stackoverflow.com/questions/72834988/react-query-makes-component-to-rerender-multiple-times

my best guess is that `setState` triggers one render, and then `useQuery` re-renders again. But those _should_ be deduped....

here's a failing test-case to reproduce:

```
  it('should not render too often when query key changes', async () => {
    const key = queryKey()
    const states: UseQueryResult<{ count: number }>[] = []

    function Page() {
      const [count, setCount] = React.useState(0)
      const state = useQuery([key, count], async () => {
        await sleep(10)
        return { count }
      })
      states.push(state)

      return (
        <div>
          <h1>data: {state.data?.count}</h1>
          <button
            onClick={() => {
              setCount(prev => prev + 1);
            }}
          >
            Next
          </button>
        </div>
      );
    }

    const rendered = renderWithClient(queryClient, <Page />)

    await waitFor(() => rendered.getByText('data: 0'))

    // Initial
    expect(states[0]).toMatchObject({ status: 'loading', data: undefined })
    // loaded
    expect(states[1]).toMatchObject({ status: 'success', data: { count: 0 } })

    expect(states.length).toBe(2)

    fireEvent.click(rendered.getByRole('button', { name: /next/i }))

    await waitFor(() => rendered.getByText('data: 1'))

    // fetching with new key
    expect(states[2]).toMatchObject({ status: 'loading', data: undefined })
    // loaded
    expect(states[3]).toMatchObject({ status: 'success', data: { count: 0 } })

    expect(states.length).toBe(4)
  })
```

**Comment by TkDodo** [comment]
Note: this used to work in `3.5.11`, but no longer in `3.5.12`

see:
- https://github.com/TanStack/query/pull/1608

**Comment by karol-janik** [comment]
Hello, is it still available? I would like to try to work on it. Thanks!

**Comment by TkDodo** [comment]
@karol-janik sure, go ahead. Thank you 🙏

**Comment by abacaj** [comment]
This appears to be the order of operations when the query key changes:
```
1. click button -> updates key state
2. build new query (status: 'loading', fetchStatus: 'fetching', optimistic)
3. dispatch fetch
4. notify listeners -> this seems to be the culprit
```

states.length counts after each operation:
```
1. 3
2. 3
3. 3
4. 4 -> this is the extra update where (status: 'loading' and fetchStatus: 'fetching')
```

The issue is there is a state update that changes key which rerenders
and then also a observer that fires the same state and also rerenders -> which puts at 5 states when the request is successful.

Seems solution might be to disable the redundant notify on key changes?

**Comment by karol-janik** [comment]
I noticed that this [`setState`](https://github.com/TanStack/query/blob/beta/src/reactjs/useBaseQuery.ts#L71) causes the loading status to duplicate itself. By replacing this hookup with `useMemo` it seems that everything works as it should. Unfortunately for this, other test casses are crashing (Probably by `defaultedOptions` in the dependency array of useMemo).

**Comment by abacaj** [comment]
@karol-janik I'm not sure we can prevent/memo the change.

Might be easier to not fire the "fetch" event from react-query observer when the key changes since this is an extra event that causes the extra "loading" state to appear.

**Comment by farzd** [comment]
is this still an issue ? i'm on ``` "@tanstack/react-query": "^4.0.9"``` and seeing this behaviour on react native
```
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2"
```

**Comment by laurentDellaNegra** [comment]
It seems to be the same issue in the practice of React Query lesson:
https://codesandbox.io/s/solution-render-optimizations-v1rgki?from-embed

There is 3 re-renders instead of 2

**Comment by TkDodo** [comment]
> There is 3 re-renders instead of 2

remove `React.StrictMode` from the example and the render count goes down to 2. This is _not_ related.

**Comment by suheth** [comment]
Is this issue fixed?

**Comment by TkDodo** [comment]
@abacaj do all tests pass with your change? Please read the comment above ⬆️ . I think it is not guaranteed that calling `setState` will actually trigger a re-render, so we need to inform observers. But I think these should actually be batched together. It might just be an issue with `useSyncExternalStore`:

- https://github.com/facebook/react/issues/25191
- https://github.com/facebook/react/issues/24831

**Comment by TkDodo** [comment]
seems like this indeed an upstream issue that rtk-query has as well:
- https://github.com/reduxjs/react-redux/issues/1912

**Comment by SaadUrRehmanBaig** [comment]
Remove strict mode from index.js as it is causing mount , unmount and remount which is causing it to render multiple times.

**Comment by SaadUrRehmanBaig** [comment]
I think i have solved the problem it was with the dependency array in the use Effect just put an empty array it will solve the problem.
<img width="1431" alt="use effect with empty dependency array" src="https://user-images.githubusercontent.com/52096646/205431307-db431317-a307-43bb-a51b-e00e61a84960.png">
<img width="1431" alt="useEffect with no dependency array" src="https://user-images.githubusercontent.com/52096646/205431310-00de198a-87ec-4f2f-a795-87be1373dcdf.png">

**Comment by kmarkiewicz** [comment]
Is there any workaround to avoid the unnecessary render?

**Comment by Ram4GB** [comment]
Sorry @SaadUrRehmanBaig but It just happens on the next query. In the author's example, The issue will happens when we click the next button. Please check this again.

On your case, we have:
```
1. useQuery fetching with loading = true
2. render
3. useEffect with no depedencies
4. useQuery finished with loading = false
5. re-render
6.  useEffect with no depedencies
```

**Comment by TkDodo** [comment]
it should be fixed when the bugs in react are fixed 🤷

**Comment by incepter** [comment]
I think the same issue is addressed in https://github.com/TanStack/query/issues/5538; and [this PR](https://github.com/TanStack/query/pull/5573) may solve it.

**Comment by TkDodo** [comment]
amazing @incepter 🙌

**Comment by daniel-ricado** [comment]
looks like thePR has been reverted? Using refetchInterval seems to cause full page re renders

**Comment by TkDodo** [comment]
@daniel-ricado the PR has not been reverted. If you see behaviour you don't expect, please file a separate issue with a new reproduction

**Comment by daniel-ricado** [comment]
hmmm bumping up the version didn't resolve it, but I'm thinking it's refreshing all children of the component it's used in. yup will setup a reproduction example and new issue if thats the case cheers.

**Comment by backspacev9** [comment]
It worked for me with request aborting
  const queryClient = useQueryClient();
  useEffect(() => {
    if (data) {
       queryClient.cancelQueries({queryKey: ["key"]}); 
    }
  }, [data]);
