### ISSUE TITLE
No QueryClient set with PNPM

### ISSUE THREAD

**Issue by accordionpeas** [TanStack/query#6083]
### Describe the bug

Hello,

Firstly, thank you for this library, It's fantastic - I have been using it for many years.

I have recently tried to migrate my monorepo project to pnpm - after a lot of effort, everything seems to be working except for this error thrown by @tanstack/react-query. 

Within the monorepo I have apps that import @tanstack/react-query, as well as packages that also import @tanstack/react-query, and are in turn imported by the app(s). The app uses @tanstack/react-query to prefetch some queries on the server and as well as making queries in the browser.

The prefetched queries seem to work fine - the server returns the hydrated HTML with the correct data. However, once the client JS loads the error is thrown - `No QueryClient set, use QueryClientProvider to set one`.

I have created a minimal example here - https://github.com/accordionpeas/react-query-pnpm-demo

The first commit contains code that does not import a local package that itself imports @tanstack/react-query - this works fine. The second commit (HEAD of `main`) shows the error.

Things I have tried to resolve this issue:
- Looking through issues in this repo - there are some similar issues and I have tried workarounds suggested in those threads but with no luck
- I have ensured the same version of @tanstack/react-query is imported throughout the project
- I have tried hoisting @tanstack/react-query and @tanstack/query-core with `public-hoist-pattern`
- I have tried removing all workspace dependencies of @tanstack/react-query and installing in the root workspace instead.

Any help would be greatly appreciated.

### Your minimal, reproducible example

https://github.com/accordionpeas/react-query-pnpm-demo

### Steps to reproduce

- Clone the demo repo
- Install - `pnpm i`
- Build - `pnpm run build`
- Run - `pnpm run start`
- Visit - `http://localhost:4321`

### Expected behavior

I expect the error not to be thrown and to work as normal

### How often does this bug happen?

Every time

### Platform

- OS: macOS
- Browser: Chrome
- Version: 117

### Tanstack Query adapter

None

### TanStack Query version

v4.33.0

### TypeScript version

v4.9.5

**Comment by TkDodo** [comment]
your dependency setup looks correct. However, I can see two versions of react-query in the resulting bundle, which is the cause of the error. It must be bundling related. I'd suggest to try to simplify it a bit. 160 lines of custom webpack config seems like a good candidate. We are using pretty much the same pattern (pnpm monorepo, QueryClientProvider in one package, useQuery in another), and we also had issues with this in pnpm v7 (basically [this](https://github.com/pnpm/pnpm/issues/5351#issuecomment-1273610927), but it doesn't apply to your situation). However, those have been addressed in pnpm. We use a standard next-js app without a custom build config, and everything builds fine with that.

**Comment by accordionpeas** [comment]
Thanks for the response. That's a fair point about the webpack config - I've simplified it and got it working - I've pushed a working version on the demo repo.

This has made me realise what is causing the error - if I change my tsconfig from `"module": "commonjs"` to  `"module": "ESNext"` then error is there.

Do you have any idea why that might be? I need `ESNext` to get loadable components to work.

**Comment by TkDodo** [comment]
hm no, sorry. we use `"module": "es2020"` and it works fine

**Comment by accordionpeas** [comment]
`es2020` also doesn't work. The only module option that seems to work is `commonjs`

**Comment by accordionpeas** [comment]
For anyone who comes across this issue - adding the following to my webpack config seems to have solved it.

```
resolve: {
    alias: {
        "@tanstack/react-query": require.resolve('@tanstack/react-query', '../../')
    }
}
```

**Comment by emzet93** [comment]
> For anyone who comes across this issue - adding the following to my webpack config seems to have solved it.
> 
> ```
> resolve: {
>     alias: {
>         "@tanstack/react-query": require.resolve('@tanstack/react-query', '../../')
>     }
> }
> ```

@accordionpeas thank you so much, I was struggling with the same issue for two days 🙏
But out of curiosity, have you ever discovered why this alias is needed and what the original problem is?
I have it working on web now with this webpack change but it is still failing for the same reason on react-native side.

**Comment by accordionpeas** [comment]
Hi @emzet93, sorry no I'm not sure what the original problem is. Once I found this fix, I stopped wasting time on it. Good luck!

**Comment by emzet93** [comment]
Thanks! I managed to fix my react native setup by adding the same alias in babel.
My thought is that if this alias helps, then it could mean that there are multiple different versions of `@tanstack/react-query` indeed. However I double checked that and there is only one. 

Anyway, I'm happy it works now. Thanks again.
